"""Initial migration.

Revision ID: f327aaed7a02
Revises: 
Create Date: 2022-11-14 10:57:28.078755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f327aaed7a02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.String(length=255), nullable=True),
    sa.Column('rut', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_office',
    sa.Column('branch_office_id', sa.Integer(), nullable=False),
    sa.Column('branch_office', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('commune_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('principal_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('visibility_id', sa.Integer(), nullable=True),
    sa.Column('opening_date', sa.Integer(), nullable=True),
    sa.Column('dte_code', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_office_id')
    )
    op.create_table('branch_office_transbanks',
    sa.Column('branch_office_transbank_id', sa.Integer(), nullable=False),
    sa.Column('branch_office_id', sa.String(length=255), nullable=True),
    sa.Column('transbank_code', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_office_transbank_id'),
    sa.UniqueConstraint('branch_office_id')
    )
    op.create_table('communes',
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.Column('commune', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('commune_id')
    )
    op.create_table('contract_type',
    sa.Column('contract_type_id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('contract_type_id')
    )
    op.create_table('document_employees',
    sa.Column('document_employees_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('support', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_employees_id')
    )
    op.create_table('document_type',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('documents_group_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_type_id')
    )
    op.create_table('documents_group',
    sa.Column('documents_group_id', sa.Integer(), nullable=False),
    sa.Column('documents_group', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('documents_group_id')
    )
    op.create_table('employee_labor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('contract_type_id', sa.Integer(), nullable=True),
    sa.Column('branch_office_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('commune_id', sa.Integer(), nullable=True),
    sa.Column('civil_state_id', sa.Integer(), nullable=True),
    sa.Column('health_id', sa.Integer(), nullable=True),
    sa.Column('pention_id', sa.Integer(), nullable=True),
    sa.Column('job_position_id', sa.Integer(), nullable=True),
    sa.Column('entrance_company', sa.Date(), nullable=True),
    sa.Column('exit_company', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('gratification', sa.Integer(), nullable=True),
    sa.Column('collation', sa.Integer(), nullable=True),
    sa.Column('locomotion', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('father_lastname', sa.String(length=255), nullable=True),
    sa.Column('mother_lastname', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('cellphone', sa.String(length=100), nullable=True),
    sa.Column('born_date', sa.Date(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healths',
    sa.Column('health_id', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(length=255), nullable=True),
    sa.Column('health_remuneration_code', sa.Integer(), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('code_previred', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('health_id')
    )
    op.create_table('nationalities',
    sa.Column('nationality_id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nationality_id')
    )
    op.create_table('pentions',
    sa.Column('pentions_id', sa.Integer(), nullable=False),
    sa.Column('pentions', sa.String(length=255), nullable=True),
    sa.Column('pentions_remuneration_code', sa.Integer(), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('code_previred', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pentions_id')
    )
    op.create_table('principal',
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('region_remuneration_code', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('rols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('supervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_office_id', sa.Integer(), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('zone')
    op.drop_table('supervisor')
    op.drop_table('segment')
    op.drop_table('rols')
    op.drop_table('regions')
    op.drop_table('principal')
    op.drop_table('pentions')
    op.drop_table('nationalities')
    op.drop_table('healths')
    op.drop_table('genders')
    op.drop_table('employees')
    op.drop_table('employee_labor_data')
    op.drop_table('documents_group')
    op.drop_table('document_type')
    op.drop_table('document_employees')
    op.drop_table('contract_type')
    op.drop_table('communes')
    op.drop_table('branch_office_transbanks')
    op.drop_table('branch_office')
    op.drop_table('audits')
    # ### end Alembic commands ###
